apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ocp-rest
message: |-
  The following secret(s) have been created in your project:
  
         Username: ${GENERATED_DB_USER}
         Password: ${GENERATED_DB_PASS}
   Connection URL: postgresql://postgresql:5432/
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: postgresql
  stringData:
    database-user: "${GENERATED_DB_USER}"
    database-password: "${GENERATED_DB_PASS}"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ocp-rest-api
    name: ocp-rest-api
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ocp-rest-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
    creationTimestamp: null
    labels:
      app: postgresql
  spec:
    ports:
      - name: postgresql
        protocol: TCP
        port: 5432
        targetPort: 5432
    selector:
      name: postgresql
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: postgresql
    creationTimestamp: null
    labels:
      app: postgresql
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - postgresql
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'postgresql:9.5'
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      name: postgresql
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: postgresql
      spec:
        volumes:
          - name: postgresql-data
            emptyDir: {}
        containers:
          - name: postgresql
            image: centos/postgresql-95-centos7
            ports:
              - containerPort: 5432
                protocol: TCP
            env:
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: database-user
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: database-password
              - name: POSTGRESQL_DATABASE
                value: ${DB_NAME}
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
              - name: postgresql-data
                mountPath: /var/lib/pgsql/data
            livenessProbe:
              tcpSocket:
                port: 5432
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                    $POSTGRESQL_DATABASE -c 'SELECT 1'
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: false
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ocp-rest-api
    name: ocp-rest-api
  spec:
    replicas: 1
    selector:
      app: ocp-rest-api
      deploymentconfig: ocp-rest-api
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ocp-rest-api
          deploymentconfig: ocp-rest-api
      spec:
        replicas: 1
        containers:
        - image: ericwittmann/ocp-rest-api
          imagePullPolicy: IfNotPresent
          name: keycloak
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
             - name: DB_DRIVER_NAME
               value: postgresql
             - name: DB_CONNECTION_URL
               value: jdbc:postgresql://postgresql:5432/${DB_NAME}
             - name: DB_USER_NAME
               valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-user
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-password
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
  status: {}
parameters:
- name: GENERATED_DB_USER
  displayName: PostgreSQL Connection Username
  description: Username for PostgreSQL user that will be used for accessing the database.
  generate: expression
  from: user[A-Z0-9]{3}
  required: true
- name: GENERATED_DB_PASS
  displayName: PostgreSQL Connection Password
  description: Password for the PostgreSQL connection user.
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: DB_NAME
  displayName: Database Name
  description: The name of the Postgresql database.
  value: ocpdb
  